# Generated by Django 2.2.3 on 2019-11-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantModel',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=30)),
            ],
        ),
    ]
