# Generated by Django 2.2.3 on 2019-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='contact_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='email_id',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
