# Generated by Django 2.2.3 on 2019-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20191108_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantmodel',
            name='password',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
