# Generated by Django 2.2.3 on 2019-11-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_merchantmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantmodel',
            name='merchant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
