# Generated by Django 2.2.3 on 2019-11-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20191109_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.MerchantModel')),
            ],
        ),
    ]
