# Generated by Django 2.2.3 on 2019-11-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoustemerModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('address', models.TextField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=15)),
            ],
        ),
    ]
