# Generated by Django 2.2.3 on 2019-11-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_coustemermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('coustemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.CoustemerModel')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.MerchantModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.ProductModel')),
            ],
        ),
    ]
